Style updates/Timeline
RocketCommunicationsInc/grm-schedule-react pull request #21
Opened 2023-06-01 21:10 UTC by Paterma

2023-06-02 18:19 UTC, Paterma commented on src/components/GlobalStatusBar/GlobalStatusBar.tsx
> +        <RuxMonitoringProgressIcon
This is not right aligned in the PDF, but, I think it looks better how Brian had it. Thoughts? We can let design decide

2023-06-02 20:55 UTC, Full-lifey requested changes
Style issues shown in the screenshots.

I will review code after these are resolved.

2023-06-02 20:56 UTC, Full-lifey commented
Segmented button is in a static location also and not responsive to the right side.
![image](https://github.com/RocketCommunicationsInc/grm-schedule-react/assets/44554249/c0da8eb7-19e1-4fb8-bb94-863d6dcccd11)

2023-06-07 13:32 UTC, Full-lifey requested changes
Great work! I just noticed that some JS template literals will clean up some repeating class names.

2023-06-07 13:32 UTC, Full-lifey commented on src/common/AstroReactTable/AstroReactTable.tsx
> +            }
You can use a template literal so you don't have to repeat the `Astro-react-table__col` class in your ternaries.

```suggestion
            className={`Astro-react-table__col ${
              isSortable && !!column.getIsSorted()
                ? 'Astro-react-table__sorted'
                : isSortable
                ? 'Astro-react-table__sortable'
                : ''
            }`}

```

2023-06-07 13:32 UTC, Full-lifey commented on src/common/AstroReactTable/AstroReactTable.tsx
> +              }
Same here, a template literal will simplify this a bit:

```suggestion
              className={`Astro-react-table__row ${
                handleIsSelected(original)
                  ? 'Astro-react-table__selected'
                  : !!onRowClick
                  ? 'Astro-react-table__selectable'
                  : ''
              }`}
```

2023-06-07 13:32 UTC, Full-lifey commented on src/components/App.tsx
> +          >
```suggestion
          <div className={`App-main__left-panel ${isOpen ? 'isOpen' : ''}`}>
```

2023-06-07 13:32 UTC, Full-lifey commented on src/components/App.tsx
> +          >
```suggestion
          <aside className={`App-main__right-panel ${isOpen ? 'isOpen' : ''}`}>
```

2023-06-07 13:32 UTC, Full-lifey commented on src/components/GlobalStatusBar/GlobalStatusBar.tsx
> +        <RuxMonitoringProgressIcon
It's good

2023-06-07 15:12 UTC, merged