Update Add Contact Drawer Panel
RocketCommunicationsInc/grm-schedule-react pull request #26
Opened 2023-06-08 20:42 UTC by Full-lifey

2023-06-08 20:58 UTC, Full-lifey commented on src/Types/generateOptions.ts
> +  passes: { id: string; aos: string; los: string }[];
I'm not sure why this was optional as it's built when first ran. It was causing a lot of downstream checks for existence.

2023-06-08 20:58 UTC, Full-lifey commented on src/components/App.css
> +  --top-deduction: 6rem;
This was causing a large gap on my screen at the bottom. I tested this by resizing and this size puts the container + padding at the bottom correctly.

2023-06-08 20:58 UTC, Full-lifey commented on src/components/App.css
> +  height: calc(100% - 44px);
The container was overflowing the parent causing some bottom content to get cut off like a horizonal scroll bar, the last item in the list, and the footers in the right panel.

2023-06-08 20:58 UTC, Full-lifey commented on src/components/GlobalStatusBar/GlobalStatusBar.tsx
> +];
I added this `RangeItem` array to solve errors in the console.

2023-06-08 20:58 UTC, Full-lifey commented on src/components/ManageContacts/ContactDetails.tsx
> -);
Moved this input up to a common component as it is used at least 25 times. It only saves two props from the overall code but it seemed worth it with such large usage.

2023-06-08 21:21 UTC, Paterma requested changes
Great work. A few things though- it throws this error when you click "Add Contact" on the confirm screen and the page goes blank, so right now adding a contact doesn't work.
![Screenshot 2023-06-08 at 3 09 23 PM](https://github.com/RocketCommunicationsInc/grm-schedule-react/assets/97068764/09e51d40-4020-497b-83fa-5a95145ccd0b)

There's a few style things as well, like the alignment of the icons. Are we going to do the arrows, too?
<img width="1098" alt="Screenshot 2023-06-08 at 3 14 11 PM" src="https://github.com/RocketCommunicationsInc/grm-schedule-react/assets/97068764/7e735871-fe6e-41c2-895c-2b9e3be0b1df">


The confirm screen needs some adjustment on the text and buttons. 
<img width="1123" alt="Screenshot 2023-06-08 at 3 15 01 PM" src="https://github.com/RocketCommunicationsInc/grm-schedule-react/assets/97068764/9ef08a0a-cd3a-4c15-897e-bc85655a4776">


What about the pass range section?
<img width="404" alt="Screenshot 2023-06-08 at 3 19 21 PM" src="https://github.com/RocketCommunicationsInc/grm-schedule-react/assets/97068764/f955f2ec-c560-4f5b-becc-df81fb939813">

2023-06-09 14:36 UTC, Full-lifey commented
> Great work. A few things though- it throws this error when you click "Add Contact" on the confirm screen and the page goes blank, so right now adding a contact doesn't work. ![Screenshot 2023-06-08 at 3 09 23 PM](https://user-images.githubusercontent.com/97068764/244508132-09e51d40-4020-497b-83fa-5a95145ccd0b.png)
> 
> There's a few style things as well, like the alignment of the icons. Are we going to do the arrows, or details, too? <img alt="Screenshot 2023-06-08 at 3 14 11 PM" width="1098" src="https://user-images.githubusercontent.com/97068764/244508312-7e735871-fe6e-41c2-895c-2b9e3be0b1df.png">
> 
> The confirm screen needs some adjustment on the text and buttons. <img alt="Screenshot 2023-06-08 at 3 15 01 PM" width="1123" src="https://user-images.githubusercontent.com/97068764/244508353-9ef08a0a-cd3a-4c15-897e-bc85655a4776.png">
> 
> What about the pass range section? <img alt="Screenshot 2023-06-08 at 3 19 21 PM" width="404" src="https://user-images.githubusercontent.com/97068764/244509029-f955f2ec-c560-4f5b-becc-df81fb939813.png">

1. Error resolved. Needed to force the user away from the confirm panel
2. The arrows and select icon to render inputs functionality was too much to add to this PR. There are too many pieces here to include in this already large body of work.
3. Confirm screen has been adjusted
4. The pass range section is functionality that doesn't make sense for the depth of our data as well as being inputs that don't exist in astro. I made the decision not to include those inputs.

2023-06-09 20:48 UTC, Paterma approved these changes

2023-06-10 04:39 UTC, NicDominguez approved these changes

2023-06-12 17:29 UTC, merged