Filter Contacts Drawer Panel
RocketCommunicationsInc/grm-schedule-react pull request #32
Opened 2023-07-13 22:08 UTC by Paterma

2023-07-18 00:47 UTC, NicDominguez requested changes
Impressive work to make this thing actually function!! I just have some recommendations for refactoring. You have some opportunity to DRY out your code a bit and make it less verbose. Please make another pass and i'll do another quick review.

2023-07-18 00:47 UTC, NicDominguez commented on src/components/ManageContacts/FilterContacts/FilterContacts.tsx
> +      .map((cb) => cb.value as Priority);
See if you can use Array.reduce for this to prevent multiple loops (https://stackoverflow.com/questions/34398279/map-and-filter-an-array-at-the-same-time)

2023-07-18 16:58 UTC, Paterma commented on src/components/ManageContacts/FilterContacts/FilterContacts.tsx
> +      .map((cb) => cb.value as Priority);
flatMap() worked best here (saw it in your link)- good suggestion.

2023-07-19 15:32 UTC, NicDominguez approved these changes

2023-07-19 15:32 UTC, merged